#!/bin/sh
# description "synchronizes kernel module"
# author "Scaleway <opensource@scaleway.com>"

dns_resolv() {
    ping -c1 $1 | sed -n -E -e 's/^PING .*\(([0-9]*(\.[0-9.]*){3})\).*$/\1/p; q'
}

CEPH_IP=${CEPH_IP:-"$( dns_resolv ceph-scw-priv1.elnounch.net. ),$( dns_resolv ceph-scw-priv2.elnounch.net. ),$( dns_resolv ceph-scw-priv3.elnounch.net. )"}
CEPH_USER=${CEPH_USER:-"guest"}
CEPH_SECRET=${CEPH_SECRET:-"AQAmqepWkcjtLhAAu5oKHicEdfSPG2jnvCUwmg=="}

MODULES_DIR=/lib/modules
mkdir -p ${MODULES_DIR}
MIRROR_DIR=/media/scaleway-mirror

KVERSION=$( uname -r )
KARCH=$( uname -m )

export PATH="${PATH:+$PATH:}/usr/bin:/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin"

module_ins() {
    [ -e ${MODULES_DIR}.local/${KVERSION}/kernel/$1 ] || {
        mkdir -p ${MODULES_DIR}.local/${KVERSION}/kernel/$(dirname $1)
        wget -q -O ${MODULES_DIR}.local/${KVERSION}/kernel/$1 http://169.254.42.24/kernel/${KARCH}/${KVERSION}/modules/${KVERSION}/kernel/$1
    }
    insmod ${MODULES_DIR}.local/${KVERSION}/kernel/$1
}

( grep -q -E -e "^[^ ]+ ${MIRROR_DIR} " /proc/mounts ) || {
    [ -d /sys/module/cbc/ ] || module_ins crypto/cbc.ko
    [ -d /sys/module/libcrc32c/ ] || module_ins lib/libcrc32c.ko
    [ -d /sys/module/libceph/ ] || module_ins net/ceph/libceph.ko
    [ -d /sys/module/fscache/ ] || module_ins fs/fscache/fscache.ko
    [ -d /sys/module/ceph/ ] || module_ins fs/ceph/ceph.ko
    [ -d ${MIRROR_DIR} ] || mkdir -p ${MIRROR_DIR}
    mount -t ceph -o "ro,name=${CEPH_USER},secret=${CEPH_SECRET},nodev,nosuid" ${CEPH_IP}:/ ${MIRROR_DIR}
} 2> /dev/null

( grep -q -E -e "^[^ ]+ ${MODULES_DIR}/${KVERSION} " /proc/mounts ) || {
    [ -d ${MODULES_DIR}/${KVERSION} ] || mkdir -p ${MODULES_DIR}/${KVERSION}
    mount -o bind,ro ${MIRROR_DIR}/kernel/${KARCH}/${KVERSION}/modules/${KVERSION} ${MODULES_DIR}/${KVERSION}
}
